### ISSUE TITLE
prevent first time popup

### ISSUE THREAD

**Issue by alex-wilmer** [Windscribe/react-scripts-ws-webextension#4]
are there flags to prevent this popup on fresh starts?

![image](https://user-images.githubusercontent.com/2880089/43295888-005a0528-9116-11e8-956b-d9b1367a707c.png)

**Comment by yegors** [comment]
https://peter.sh/experiments/chromium-command-line-switches/

I think this should do the trick 
```--disable-default-apps```

**Comment by alex-wilmer** [comment]
sweet
